{% set name = "pyswmm" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8034b9d9b9bf42867c75564a07c386864618dadbb3560e2da902a195422d5f2
  patches:
    - __init__.py.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - six
    - swmm

about:
  home: https://github.com/OpenWaterAnalytics/pyswmm/wiki
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Wrapper for SWMM5 API
  doc_url: https://pyswmm.readthedocs.io
  dev_url: https://github.com/OpenWaterAnalytics/pyswmm/

extra:
  recipe-maintainers:
    - lrntct
