{% set name = "pyswmm" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lrntct/pyswmm/releases/download/v{{ version }}%2Blocallib01/{{ name }}-{{ version }}+locallib01.tar.gz
  sha256: 6c34d347d217342f7504fa630a58ceb9a097e59a8d2847f1d4db2a14e9077780

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - six
    - swmm

test:
  imports:
    - pyswmm
    - pyswmm.lib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenWaterAnalytics/pyswmm/wiki
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python Wrapper for SWMM5 API
  doc_url: https://pyswmm.readthedocs.io
  dev_url: https://github.com/OpenWaterAnalytics/pyswmm/

extra:
  recipe-maintainers:
    - lrntct
